struct VertexInput {
    float3 pos   : POSITION;
    float3 color : COLOR;
};

struct VertexOutput {
    float4 pos   : SV_Position;
    float3 color : COLOR;
};

[shader("vertex")]
VertexOutput vertMain(VertexInput input) {
    VertexOutput output;
    output.pos   = float4(input.pos, 1.0);
    output.color = input.color;
    return output;
}

[shader("fragment")]
float4 fragMain(VertexOutput input) : SV_Target {
    return float4(input.color, 1.0);
}